name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xenotaur/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.PUSH_GATSBY }}
          deploy-branch: generated-static-pages
          gatsby-args: --prefix-paths
